# Generated by Django 3.2.23 on 2024-02-02 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(related_name='disliked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
